name: Build luci-app-xray APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install ZSTD Compiler
        run: |
          # Устанавливаем zstd, так как новые SDK OpenWrt сжаты в .tar.zst
          sudo apt-get update
          sudo apt-get install -y zstd

      - name: Setup OpenWrt SDK
        run: |
          # Скачиваем официальный SDK OpenWrt 25.12.5 (.tar.zst)
          wget --tries=10 --retry-connrefused --waitretry=5 -c https://downloads.openwrt.org/releases/25.12.5/targets/x86/64/openwrt-sdk-25.12.5-x86-64_gcc-14.3.0_musl.Linux-x86_64.tar.zst
          # Распаковываем архив с поддержкой zstd
          tar --zstd -xf openwrt-sdk-25.12.5-x86-64_gcc-14.3.0_musl.Linux-x86_64.tar.zst
          # Переименовываем каталог в sdk
          mv openwrt-sdk-25.12.5-x86-64_gcc-14.3.0_musl.Linux-x86_64 sdk

      - name: Update and Install Feeds
        run: |
          cd sdk
          echo "src-git-full luci_app_xray https://github.com" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure Package
        run: |
          cd sdk
          make defconfig
          echo "CONFIG_PACKAGE_luci-app-xray=m" >> .config
          make defconfig

      - name: Compile Package
        run: |
          cd sdk
          make package/luci-app-xray/compile V=s IGNORE_ERRORS=1

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-xray-apk-x86_64
          path: |
            sdk/bin/packages/x86_64/base/*.apk
            sdk/bin/packages/x86_64/luci/*.apk
          if-no-files-found: error

